stages:
  - test

test:
  stage: test
  image: golang:1.21
  script:
    - go test -v -coverprofile=coverage.out -covermode=count ./...
    - go install github.com/jstemmer/go-junit-report/v2@latest
    - go test -v ./... | go-junit-report -set-exit-code > report.xml
  artifacts:
    paths:
      - coverage.out
      - report.xml
    expire_in: 1 week