name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: false

      - name: Run linter
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          args: --timeout=3m --out-format=colored-line-number

      - name: Run tests with coverage and report
        run: |
          mkdir -p test-results
          go test ./... -v -coverprofile=test-results/coverage.out -covermode=atomic 2>&1 | tee test-results/test.log
          go tool cover -html=test-results/coverage.out -o test-results/coverage.html
          go install github.com/jstemmer/go-junit-report/v2@latest
          cat test-results/test.log | go-junit-report -set-exit-code > test-results/test-report.xml

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: |
            test-results/coverage.out
            test-results/coverage.html
            test-results/test.log
            test-results/test-report.xml
          retention-days: 7
          if-no-files-found: warn
